# Generated by Django 5.1.7 on 2025-04-30 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(choices=[('Python developer', 'pythondeveloper'), ('mearn stack', 'mearnstack'), ('digital marketing', 'digitalmarketing'), ('graphic design', 'graphicdesign')], default='python developer', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('image', models.ImageField(default='project_pic/default', upload_to='project_pic')),
                ('link', models.CharField(max_length=300)),
                ('project_discription', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('job_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobs')),
            ],
        ),
    ]
