# Generated by Django 5.0.6 on 2025-05-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='job',
            field=models.CharField(choices=[('pythondeveloper', 'pythondeveloper'), ('mearnstack', 'mearnstack'), ('digitalmarketing', 'digitalmarketing'), ('graphicdesign', 'graphicdesign')], default='pythondeveloper', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default='project_pic/default.png', null=True, upload_to='project_pic'),
        ),
    ]
