# Generated by Django 5.0.6 on 2025-05-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_career_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='job',
            field=models.CharField(choices=[('Python Developer', 'Python Developer'), ('Mern Stack', 'mearnstack'), ('Digital Marketing', 'digitalmarketing'), ('Graphic Design', 'graphicdesign')], default='pythondeveloper', max_length=200),
        ),
    ]
